#!/bin/bash

./zaZipUpScript.txt
./zbFileCopyScript.txt
./zcCompileScript.txt
./zdExecuteScript.txt

cd testdirectory/harmonethan_sourceremoval_program3/
./Aprog xingraph1.txt zoutfile1.txt zlogfile1.txt
./Aprog xingraph11.txt zoutfile11.txt zlogfile11.txt
./Aprog xingraph2.txt zoutfile2.txt zlogfile2.txt
./Aprog xingraph3.txt zoutfile3.txt zlogfile3.txt
./Aprog xingraph4.txt zoutfile4.txt zlogfile4.txt
./Aprog xingraphPRQ.txt zoutfilePRQ.txt zlogfilePRQ.txt
